package com.noker.helpers.model;

import java.io.Serializable;

public class Location implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.province_en
     *
     * @mbggenerated
     */
    private String provinceEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.city_en
     *
     * @mbggenerated
     */
    private String cityEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.district
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.district_en
     *
     * @mbggenerated
     */
    private String districtEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table location
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.id
     *
     * @return the value of location.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.id
     *
     * @param id the value for location.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.province
     *
     * @return the value of location.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.province
     *
     * @param province the value for location.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.province_en
     *
     * @return the value of location.province_en
     *
     * @mbggenerated
     */
    public String getProvinceEn() {
        return provinceEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.province_en
     *
     * @param provinceEn the value for location.province_en
     *
     * @mbggenerated
     */
    public void setProvinceEn(String provinceEn) {
        this.provinceEn = provinceEn == null ? null : provinceEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.city
     *
     * @return the value of location.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.city
     *
     * @param city the value for location.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.city_en
     *
     * @return the value of location.city_en
     *
     * @mbggenerated
     */
    public String getCityEn() {
        return cityEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.city_en
     *
     * @param cityEn the value for location.city_en
     *
     * @mbggenerated
     */
    public void setCityEn(String cityEn) {
        this.cityEn = cityEn == null ? null : cityEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.district
     *
     * @return the value of location.district
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.district
     *
     * @param district the value for location.district
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.district_en
     *
     * @return the value of location.district_en
     *
     * @mbggenerated
     */
    public String getDistrictEn() {
        return districtEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.district_en
     *
     * @param districtEn the value for location.district_en
     *
     * @mbggenerated
     */
    public void setDistrictEn(String districtEn) {
        this.districtEn = districtEn == null ? null : districtEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Location other = (Location) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getProvinceEn() == null ? other.getProvinceEn() == null : this.getProvinceEn().equals(other.getProvinceEn()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCityEn() == null ? other.getCityEn() == null : this.getCityEn().equals(other.getCityEn()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getDistrictEn() == null ? other.getDistrictEn() == null : this.getDistrictEn().equals(other.getDistrictEn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getProvinceEn() == null) ? 0 : getProvinceEn().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCityEn() == null) ? 0 : getCityEn().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getDistrictEn() == null) ? 0 : getDistrictEn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", province=").append(province);
        sb.append(", provinceEn=").append(provinceEn);
        sb.append(", city=").append(city);
        sb.append(", cityEn=").append(cityEn);
        sb.append(", district=").append(district);
        sb.append(", districtEn=").append(districtEn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}